import React, { useState, useMemo } from 'react';
import { buildForest, majorityVote, buildSurrogate } from './services/randomForest';
import { BASE_DATA } from './constants';
import Controls from './components/Controls';
import DecisionPlot from './components/DecisionPlot';
import AnalysisPanel from './components/AnalysisPanel';
import { Sprout } from 'lucide-react';

const App: React.FC = () => {
  // --- State ---
  const [nTrees, setNTrees] = useState<number>(40);
  const [seed, setSeed] = useState<number>(123);
  const [depth, setDepth] = useState<number>(3);
  
  // Test Point State
  const [testInc, setTestInc] = useState<number>(45);
  const [testScore, setTestScore] = useState<number>(650);

  // --- Derived State (Memoized logic) ---
  
  // 1. Build Forest
  const forest = useMemo(() => {
    return buildForest(BASE_DATA, nTrees, seed);
  }, [nTrees, seed]);

  // 2. Voting for current test point
  const testPoint = useMemo(() => ({ inc: testInc, score: testScore }), [testInc, testScore]);
  const voteResult = useMemo(() => majorityVote(forest, testPoint), [forest, testPoint]);

  // 3. Build Surrogate Tree
  const surrogateRoot = useMemo(() => {
    return buildSurrogate(BASE_DATA, forest, depth);
  }, [forest, depth]);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 pb-12">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-indigo-600 p-1.5 rounded-lg text-white">
                <Sprout size={20} />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-slate-900">ForestLogic <span className="font-normal text-slate-500 hidden sm:inline">| Loan Decision Visualizer</span></h1>
          </div>
          <a href="#" className="text-sm font-medium text-indigo-600 hover:text-indigo-500">
            View Source
          </a>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Left Column: Controls & Stats */}
          <div className="lg:col-span-4 space-y-6">
            <Controls 
              nTrees={nTrees} setNTrees={setNTrees}
              seed={seed} setSeed={setSeed}
              depth={depth} setDepth={setDepth}
              testInc={testInc} setTestInc={setTestInc}
              testScore={testScore} setTestScore={setTestScore}
            />
            
            <AnalysisPanel 
              voteResult={voteResult}
              surrogateRoot={surrogateRoot}
            />
          </div>

          {/* Right Column: Visualization */}
          <div className="lg:col-span-8">
             <div className="sticky top-24">
                <DecisionPlot forest={forest} testPoint={testPoint} />
                
                <div className="mt-6 bg-blue-50 border border-blue-100 rounded-lg p-4">
                    <h4 className="text-sm font-bold text-blue-800 mb-1">How it works</h4>
                    <p className="text-sm text-blue-700 leading-relaxed">
                        The background heatmap represents the <strong>Random Forest's</strong> collective decision boundary. 
                        It is generated by polling {nTrees} decision trees for every pixel. 
                        The surrogate rules on the left are a simplified "white-box" explanation of this complex model.
                        Try changing the <strong>Seed</strong> to see how variance affects the decision boundaries!
                    </p>
                </div>
             </div>
          </div>

        </div>
      </main>
    </div>
  );
};

export default App;
